### ISSUE TITLE
Provide a way to turn the UUID into a String again

### ISSUE THREAD

**Issue by i-am-the-slime** [spicydonuts/purescript-uuid#12]
I would like to generate a UUID for a database ID. So I need to turn it into a different String Newtype. I could show and cut things off but that's hideous.

**Comment by maddie927** [comment]
Hmm, do you think I should just change the Show instance or add a new `UUID -> String` function?

**Comment by i-am-the-slime** [comment]
I usually prefer toString, never trust Show. But it's up to you of course.

**Comment by maddie927** [comment]
That works for me

**Comment by maddie927** [comment]
Closed by v6.0.0
