### ISSUE TITLE
Bump up package-sets

### ISSUE THREAD

**Issue by CGenie** [spicydonuts/purescript-uuid#29]
On https://github.com/purescript/package-sets/releases/tag/psc-0.15.0-20220509 I'm still getting that `uuid` does not exist in the package set even though I see in commits that this is ported to 0.15.0.

**Comment by maddie927** [comment]
I think this might be automatic once a new version is tagged, but there's a missing dependency not in the 0.15 package set yet, `foreign-generic`

**Comment by cscalfani** [comment]
According to Thomas Honeyman, `foreign-generic` is not maintained: https://discourse.purescript.org/t/purescript-0-15-library-status-question/3063/2?u=cscalfani

The only real usage for `foreign-generic` appears to be in test code. Nowhere in the library proper.

Maybe just remove that 1 line of test code and then this can be part of the `spago` package set.
