### ISSUE TITLE
Add support for PS `0.15`

### ISSUE THREAD

**Issue by JordanMartinez** [spicydonuts/purescript-uuid#30]

**Comment by cscalfani** [comment]
Did you see https://github.com/megamaddu/purescript-uuid/issues/29?

Evidently, `foreign-generic` isn't 0.15 compatible.

**Comment by cscalfani** [comment]
There's a pull request for `foreign-generic` to update it to 0.15 https://github.com/paf31/purescript-foreign-generic/pull/76

**Comment by JordanMartinez** [comment]
Ah... I'll close this then.
