### ISSUE TITLE
Package `uuid` does not exist in package set

### ISSUE THREAD

**Issue by IsolaMonte** [spicydonuts/purescript-uuid#9]
I recently bumped my PureScript pgk set to `psc-0.12.2` and wanted to add this pkg as a dependency. Installing the npm part works fine (`npm install -S uuid uuid-validate`) but when attempting to install the PureScript parts `psc-package install uuid` and `psc-package install uuid-validate` I get this error:
```Package `uuid` does not exist in package set```

Is this related to the build failing (https://travis-ci.org/spicydonuts/purescript-uuid) perhaps? Or am I missing something else?

**Comment by maddie927** [comment]
I'm not too familiar with psc-package but I believe each package set is managed [here](https://github.com/purescript/package-sets). That project probably needs a PR to include this library in the next set.

I looked into the failing build and it seems to have just been an out of date `bower` exe (pointing to a deprecated cdn, couldn't install the PS libraries for testing). That wouldn't impact being able to use this library as a dependency or the psc-package package set verification scripts (if any, I'm not familiar with it, sorry!)

**Comment by maddie927** [comment]
I pushed a new patch release to fix the build and bump a few dependencies

**Comment by IsolaMonte** [comment]
Ok. Thanx for looking into it! 🙏

**Comment by maddie927** [comment]
Yep, let me know if you have issues. Going to close this in the meantime.
